"""/Adding

Revision ID: f3a6c421f766
Revises: 33e651a6c3a9
Create Date: 2024-02-12 02:52:31.690904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3a6c421f766"
down_revision: Union[str, None] = "33e651a6c3a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "name")
    # ### end Alembic commands ###
